import "../styles/globals.css"
import "@rainbow-me/rainbowkit/styles.css"
import { getDefaultWallets, RainbowKitProvider } from "@rainbow-me/rainbowkit"
import { chain, configureChains, createClient, WagmiConfig } from "wagmi"
import { alchemyProvider } from "wagmi/providers/alchemy"
import { publicProvider } from "wagmi/providers/public"
import { NotificationProvider } from "@web3uikit/core"
import React from "react"
import Head from "next/head"
import { WagmiProvider } from "wagmi"
import { SessionProvider } from "next-auth/react"
import { RainbowKitSiweNextAuthProvider } from "@rainbow-me/rainbowkit-siwe-next-auth"
import { AppProps } from "next/app"
import { connectorsForWallets, wallet } from "@rainbow-me/rainbowkit"

const { chains, webSocketProvider, provider } = configureChains(
    [chain.polygon, chain.polygonMumbai],
    [publicProvider()]
)
const { connectors } = getDefaultWallets({
    appName: "My RainbowKit App",
    chains,
})
const wagmiClient = createClient({
    autoConnect: true,
    connectors,
    provider,
    webSocketProvider,
})

function MyApp({ Component, pageProps }) {
    return (
        <div className="dark:bg-gray-800">
            <Head>
                <title>Protecc</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <WagmiConfig client={wagmiClient}>
                <SessionProvider session={pageProps.session} refetchInterval={0}>
                    <RainbowKitProvider chains={chains}>
                        <NotificationProvider>
                            <Component {...pageProps} />
                        </NotificationProvider>
                    </RainbowKitProvider>
                </SessionProvider>
            </WagmiConfig>
        </div>
    )
}

export default MyApp

