import { ConnectKitButton } from "connectkit";
import Head from "next/head";
import Navbar from "../Components/Header/Navbar";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            <div>
                <h1 className="text-8xl text-center mt-20 font-bold">
                    Protecc
                </h1>

                <div>
                    <p className="text-2xl px-20 mt-7 text-center">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Donec facilisis ex nec ipsum molestie, a lacinia arcu
                        sollicitudin. Aenean justo lacus, euismod molestie
                        finibus sit amet, sodales nec sem. Suspendisse eget
                        luctus orci, et egestas mauris. Donec efficitur feugiat
                        tincidunt.
                    </p>
                </div>

                <div className="grid v-screen place-items-center mt-10">
                    <ConnectKitButton />
                </div>
            </div>
        </div>
    );
}
